ARG SPLUNK_VERSION=latest
FROM splunk/splunk:$SPLUNK_VERSION
ARG SPLUNK_VERSION=latest
ARG SPLUNK_APP_ID=TA_UNKNOWN
ARG SPLUNK_APP_PACKAGE=package
RUN echo ${SPLUNK_VERSION} $SPLUNK_APP_PACKAGE
COPY deps/apps deps/build/addonfactory_test_matrix_splunk/packages/all/common deps/build/addonfactory_test_matrix_splunk/packages/all/sh /opt/splunk/etc/apps/
COPY ${SPLUNK_APP_PACKAGE} /opt/splunk/etc/apps/${SPLUNK_APP_ID}
